localaddr = ":8759"
adminaddr = ":8758"
adminbearer = "grmbl"
externaladdr = "https://localhost:8759"
loglevel = "DEBUG"
policyfile = "config/policies.toml"
tokenxor = 4192431797130687763
rndsize = 8

tokenstore = "badger"

[certname]
Organization = ["University Library Basel"]
Country = ["CH"]
Province = ["Basel City"]
Locality = ["Basel"]
StreetAddress = ["Schönbeinstrasse 18-20"]
PostalCode = ["4056"]

[badgerstore]
folder = "/tmp/minivault"
hexkey = ""
cachesize = 0

[webtls]
type = "dev"

[admintls]
type = "dev"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="miniresolver"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
ca=["certs/ca.crt"]
interval="1h"
