localaddr = ":8759"
adminaddr = ":8758"
adminbearer = "grmbl"
externaladdr = "https://localhost:8759"
loglevel = "DEBUG"
policyfile = "config/policies.toml"
tokenxor = 4192431797130687763
tokenmaxttl = "2h"
certmaxttl = "10m"
parentmaxttl = "10000h"
rndsize = 8
ca = """-----BEGIN CERTIFICATE-----
MIICxTCCAkqgAwIBAgIGAY4FTF/mMAoGCCqGSM49BAMDMIGYMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxEDAOBgNVBAMTB0R1bW15Q0EwHhcN
MjQwMzAzMTcxMTE1WhcNMzQwMzAxMTcxMTE1WjCBmDELMAkGA1UEBhMCQ0gxEzAR
BgNVBAgTCkJhc2VsIENpdHkxDjAMBgNVBAcTBUJhc2VsMSAwHgYDVQQJDBdTY2jD
tm5iZWluc3RyYXNzZSAxOC0yMDENMAsGA1UEERMENDA1NjEhMB8GA1UEChMYVW5p
dmVyc2l0eSBMaWJyYXJ5IEJhc2VsMRAwDgYDVQQDEwdEdW1teUNBMHYwEAYHKoZI
zj0CAQYFK4EEACIDYgAErHxZYoHwHzTqRg14Ve9/APs/D+sMSKDTpPTZYFocZedF
VGJEkeaCqQvsCY5G9WaHXI7jZtewKo/bHM/WcmXZB+cZNmJn/IyBHJAYh5xN5WBY
vUPJfRfQosSFr8SDE4MPo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFH+I
PuzNyAOrQ+rMTtywGqm3Z5ARMAoGCCqGSM49BAMDA2kAMGYCMQDJNau3j1v1FQHQ
n7kn+gEATGOm+9fBsgUCGXmKvLZPIJI3NI2URLmlmASdEIrg/N4CMQCNQio9BHom
JYLotIXmdUEmKuXZeKoc0eR1jA7kWdJNOvEpE73mx/zutDeNl3hRVP0=
-----END CERTIFICATE-----"""

cakey = """-----BEGIN EC PRIVATE KEY-----
MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDCSr6Ye4kOH8K8/rVPk
XMHhgnRTipYr7wvf7QtGxzoGuds5deVKBAAaU+KFB/hFhXKhZANiAASsfFligfAf
NOpGDXhV738A+z8P6wxIoNOk9NlgWhxl50VUYkSR5oKpC+wJjkb1ZodcjuNm17Aq
j9scz9ZyZdkH5xk2Ymf8jIEckBiHnE3lYFi9Q8l9F9CixIWvxIMTgw8=
-----END EC PRIVATE KEY-----
"""

capassword = "%%CA_KEY_PASS%%"

tokenstore = "badger"

[certname]
Organization = ["University Library Basel"]
Country = ["CH"]
Province = ["Basel City"]
Locality = ["Basel"]
StreetAddress = ["Schönbeinstrasse 18-20"]
PostalCode = ["4056"]

[badgerstore]
folder = "/tmp/minivault"
hexkey = ""
cachesize = 0

[webtls]
type = "dev"

[admintls]
type = "dev"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="minivault"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
