[[policy]]
    Name = "ubmedia.mediaserverdb"
    URIs = ["grpc:miniresolverproto.MiniResolver"]
    DNS = ["ubmedia.mediaserverproto.Database"]
    IPs = []
    MaxTTL = "10h"

[[policy]]
Name = "miniresolver"
URIs = []
DNS = ["localhost"]
IPs = ["127.0.0.1", "::1"]
MaxTTL = "10h"

[[policy]]
Name = "mediaserveraction"
URIs = []
DNS = ["localhost"]
IPs = ["127.0.0.1", "::1"]
MaxTTL = "10h"
